/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    DualOracle: {
      address: "0xb99d67fcf02a8750f403c610ac9acf12944444ba",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "chainlinkFeed_",
              type: "address",
              internalType: "contract IAggregatorV3",
            },
            {
              name: "chainlinkMaxAge_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "supraFeed_",
              type: "address",
              internalType: "contract ISupraSValueFeed",
            },
            {
              name: "supraPairId_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "supraMaxAge_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxDeviationBps_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "chainlinkDecimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "chainlinkFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IAggregatorV3",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "chainlinkMaxAge",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "deviationBps",
          inputs: [
            {
              name: "a",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "b",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "latestPrice",
          inputs: [],
          outputs: [
            {
              name: "priceE18",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum IPriceOracle.Status",
            },
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxDeviationBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "readChainlink",
          inputs: [],
          outputs: [
            {
              name: "ok",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "priceE18",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "readSupra",
          inputs: [],
          outputs: [
            {
              name: "ok",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "priceE18",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supraFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISupraSValueFeed",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supraMaxAge",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supraPairId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "error",
          name: "InvalidConfig",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41281914,
    },
    HbarCdpEngine: {
      address: "0x25d723a645d0767a315bd2df8b798113a644f175",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "oracle_",
              type: "address",
              internalType: "contract IPriceOracle",
            },
            {
              name: "minCollateralRatioBps_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "liquidationRatioBps_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "liquidationBonusBps_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minDebt_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "debtCeiling_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "STABLECOIN_DECIMALS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "int32",
              internalType: "int32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "acceptOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createStablecoin",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "memo",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "debtCeiling",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "depositAndMint",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getVault",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct HbarCdpEngine.VaultView",
              components: [
                {
                  name: "owner",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "collateral",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "debt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "collateralValue",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "collateralRatioBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxMintable",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxWithdrawable",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "liquidatable",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getVaults",
          inputs: [
            {
              name: "offset",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "limit",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "views",
              type: "tuple[]",
              internalType: "struct HbarCdpEngine.VaultView[]",
              components: [
                {
                  name: "owner",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "collateral",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "debt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "collateralValue",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "collateralRatioBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxMintable",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxWithdrawable",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "liquidatable",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "liquidate",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "repayAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "liquidationBonusBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "liquidationRatioBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "minCollateralRatioBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "minDebt",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mintingPaused",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "oracle",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IPriceOracle",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingOwner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "repay",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "repayAndWithdraw",
          inputs: [
            {
              name: "repayAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "withdrawAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "requiredCollateral",
          inputs: [
            {
              name: "debt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "priceE18",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "ratioBps",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "setDebtCeiling",
          inputs: [
            {
              name: "debtCeiling_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setMintingPaused",
          inputs: [
            {
              name: "paused",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stablecoin",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sweepExcessHbar",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address payable",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "totalCollateral",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalDebt",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "vaultCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "vaultOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "collateral",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "debt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DebtCeilingUpdated",
          inputs: [
            {
              name: "debtCeiling",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Deposited",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ExcessHbarSwept",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Liquidated",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "liquidator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "debtRepaid",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "collateralSeized",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "priceE18",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Minted",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MintingPausedUpdated",
          inputs: [
            {
              name: "paused",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferStarted",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Repaid",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StablecoinCreated",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "VaultUpdated",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "collateral",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "debt",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AmountTooLarge",
          inputs: [],
        },
        {
          type: "error",
          name: "DebtBelowMinimum",
          inputs: [
            {
              name: "minDebt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "DebtCeilingExceeded",
          inputs: [
            {
              name: "available",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ExceedsDebt",
          inputs: [
            {
              name: "debt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "HbarTransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "HtsCallFailed",
          inputs: [
            {
              name: "selector",
              type: "bytes4",
              internalType: "bytes4",
            },
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "InsufficientCollateral",
          inputs: [
            {
              name: "available",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidConfig",
          inputs: [],
        },
        {
          type: "error",
          name: "MintingPaused",
          inputs: [],
        },
        {
          type: "error",
          name: "NotAssociated",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "NotLiquidatable",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleUnusable",
          inputs: [
            {
              name: "status",
              type: "uint8",
              internalType: "enum IPriceOracle.Status",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "StablecoinAlreadyCreated",
          inputs: [],
        },
        {
          type: "error",
          name: "StablecoinNotCreated",
          inputs: [],
        },
        {
          type: "error",
          name: "Undercollateralised",
          inputs: [
            {
              name: "requiredCollateral",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ZeroAmount",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41281917,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
